// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a href=\"/\" class=\"flex items-center gap-2.5 font-black tracking-tight text-[var(--fg)] select-none group\"><div class=\"h-8 w-8 border-2 border-[var(--border)] p-1 flex items-center justify-center shadow-[2px_2px_0px_0px_var(--border)] transition-all group-active:translate-x-0.5 group-active:translate-y-0.5 group-active:shadow-none\"><svg viewBox=\"0 0 32 32\" fill=\"none\" class=\"h-full w-full text-[var(--fg)]\"><rect x=\"2\" y=\"2\" width=\"28\" height=\"28\" stroke=\"currentColor\" stroke-width=\"2.5\"></rect> <path d=\"M8 24 L24 8\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"square\"></path> <rect x=\"6\" y=\"20\" width=\"6\" height=\"6\" fill=\"currentColor\"></rect></svg></div><span class=\"text-sm font-black uppercase tracking-[0.15em]\">Udin's Canvas</span></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
