// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "gotth/app/components"

func CanvasPage(title string, drawingId string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"h-full\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/canvas/page.templ`, Line: 11, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — Canvas</title><link rel=\"icon\" type=\"image/jpeg\" href=\"/static/goth_lady_logo.jpg\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"anonymous\"><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Fira+Code:wght@400;700&display=swap\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"/globals.css\"><script src=\"https://unpkg.com/htmx.org@2.0.4\" integrity=\"sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+\" crossorigin=\"anonymous\"></script><script src=\"https://www.gstatic.com/firebasejs/12.15.0/firebase-app-compat.js\"></script><script src=\"https://www.gstatic.com/firebasejs/12.15.0/firebase-auth-compat.js\"></script><script src=\"https://unpkg.com/react@18/umd/react.production.min.js\"></script><script src=\"https://unpkg.com/react-dom@18/umd/react-dom.production.min.js\"></script><script src=\"https://unpkg.com/@excalidraw/excalidraw@0.17.0/dist/excalidraw.production.min.js\"></script><script>\n\t\t\t\tfirebase.initializeApp({\n\t\t\t\t\tapiKey: \"AIzaSyC4uHw6X_ugSXKqVEiio3y24LqTPTPD27w\",\n\t\t\t\t\tauthDomain: \"canvas-78802.firebaseapp.com\",\n\t\t\t\t\tprojectId: \"canvas-78802\",\n\t\t\t\t\tstorageBucket: \"canvas-78802.firebasestorage.app\",\n\t\t\t\t\tmessagingSenderId: \"384877248276\",\n\t\t\t\t\tappId: \"1:384877248276:web:61d08dffd5f19d0f358c01\",\n\t\t\t\t});\n\t\t\t</script><style>\n\t\t\t\thtml, body, #canvas-mount { height: 100%; margin: 0; padding: 0; }\n\t\t\t\t.excalidraw .App-menu_top .buttonList { display: none !important; }\n\t\t\t</style></head><body class=\"h-full flex flex-col bg-[var(--bg)] text-[var(--fg)] antialiased\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navigation("/draw/"+drawingId).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"canvas-mount\" class=\"flex-1\"></div><script>\n\t\t\t\tconst drawingId = \"{ drawingId }\";\n\t\t\t</script><script src=\"/static/bridge.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
